### PR TITLE
Use new GBFS feed for CitiBike NYC

### LINKED ISSUE #2156: CitiBike: Need to normalize dates to standard format and UTC Timezone
I realized that the date string we get from the CitiBike API (https://www.citibikenyc.com/stations/json) is a non-standard date format which the `new Date()` constructor cannot parse. Also, it's given in EDT instead of UTC, but the string doesn't indicate the timezone, causing further problems.

@marianosimone do you know if we can get CitiBike to give us a proper, UTC formatted string? As well, can you update the code to replace the `-` with `/` then convert the time to UTC (you'll probably need to set timezone for the date to EDT first)

This way when dealing with other timezones everything will be normalized :+1: 

/cc @xuv

-----
IA Page: https://duck.co/ia/view/citi_bike_nyc

### LINKED ISSUE #2745: Bike Sharing New York City (Citi Bike): IA Disabled, API URL Changed?
This IA has been taken offline because it started failing.

It looks like the URL for the API has changed and is now redirecting to a new subdomain. The `spice to` needs to be updated accordingly to get this IA online again

------
IA Page:  http://duck.co/ia/view/citi_bike_nyc 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @marianosimone

### PR DESCRIPTION
**Pull request by marianosimone**
The new GBFS feeds will be the only maintained from now on
More info: https://github.com/NABSA/gbfs/
As a side effect, #2156 is fixed, as they now use POSIX timestamps

Fixes #2745, Fixes #2156 

---
IA Page: https://duck.co/ia/view/citi_bike_nyc

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by moollaza** [comment]
@marianosimone apologies for the delay, deploying to Beta

To confirm, this IA now requires 2 calls per station?

Can the status calls be made on the frontend? After initial display?

File: share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.js [hunk 1]
```diff
@@ -16,80 +16,104 @@
...
-                        var pointOfReference = L.latLng(references[query]);
+
+                var stations_information = api_result.data.stations.reduce(function(stations, station) {
+                    stations[station.station_id] = station;
+                    return stations;
+                }, {});
+
+                var full_data = status_api_result.data.stations.map(function(station_status) {
+                    var station_information = stations_information[station_status.station_id];
+                    if (station_information) {
```
Comment (moollaza) [inline share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.js]: `$.extend()` might be a little simpler to user here?

Comment (marianosimone) [inline share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.js]: :+1: good catch

**Comment by marianosimone** [comment]
@moollaza this IA now requires two calls per query (not station): one gets the stations themselves (name, location), and a second the current status (number of available bikes, docks, etc.)

If I understand how this works, the second call IS being made in the frontend (line 30). Am I missing something?

**Comment by moollaza** [comment]
> @moollaza this IA now requires two calls per query (not station): one gets the stations themselves (name, location), and a second the current status (number of available bikes, docks, etc.)

Ah ok, thanks for clarifying. For some reason I thought something was looping in there, should have looked closer.

> If I understand how this works, the second call IS being made in the frontend (line 30). Am I missing something?

@marianosimone you're correct that it's making the request from the frontend, but what I meant was, can we make the second API call _after_ the `Spice.add()` call, using the data from the first call to build most of the Instant Answer display.

That way we only need to wait for 1 API call to start showing something to the user, rather than waiting for 2 round trips because calling `Spice.add()`

For example, the Amazon Instant Answer builds all the tiles and uses `onItemShown()` to make an additional call for each tile to request it's rating/review data.

If that's not possible though it's OK, XKCD works by making two calls to show the IA.

**Comment by marianosimone** [comment]
I see what you mean, but in this particular case I don't think it makes too much sense: Until the second call is made, there's no info on availability, which is what's more prominent on the card (we *could* show the card with just the name and something denoting that more data is being loaded... I'll let you guys decide if you think it's a good idea)

Also, it seems like handlers like `onItemShown()` don't update the DOM, so we would need some way to force the rendered template

**Comment by moollaza** [comment]
> Until the second call is made, there's no info on availability, which is what's more prominent on the card

Understood. This will be fine then 👍 

> Also, it seems like handlers like onItemShown() don't update the DOM, so we would need some way to force the rendered template

Actually they do! We pass the `item` through to the callback you define. It can call `item.set({key1: val, key2: val}});` which will update the underlying model for the item. You also need to set `meta: { rerender: ['key1', 'key2'] }` and then the DOM will automatically update when those values are changed in the model 👍 

Here's some examples: https://github.com/duckduckgo/zeroclickinfo-spice/search?utf8=%E2%9C%93&q=rerender

**Comment by moollaza** [comment]
@marianosimone Thanks! This LGTM :+1:

**Comment by marianosimone** [comment]
🎉  it got merged!!!

Just a quick note about `onItemShow`, @moollaza : I got confused by the last part of the documentation (http://docs.duckduckhack.com/frontend-reference/display-reference.html - "The item Argument" section):

> Events relevant to specific items pass an item to their handler functions. This is a reference to the item's data object, rendered to the template. Modifying the properties will not update the DOM.
