### PR TITLE
Fix airlines IA trigger and date parsing

### LINKED ISSUE #2771: Airlines: IA Disabled in Production -- No longer triggering correctly
This IA stopped working correctly and has been disabled in Production. It is still live on Beta though.

It looks like the API is still responding correctly, however there are no JS errors. Something has likely changed with the API response and so this needs further investigation to get it online again.

------
IA Page:  http://duck.co/ia/view/airlines 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @amoraleda

### PR DESCRIPTION
**Pull request by marianosimone**
Given that the original query is done using GTM time, when parsing
the data, the timezone needs to be specified as Z, instead of using
local and then requesting the UTC version of the moment object

Fixes #2771

IA Page: http://duck.co/ia/view/airlines 
Maintainer: @amoraleda

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

File: lib/DDG/Spice/Airlines.pm [hunk 1]
```diff
@@ -8,8 +8,7 @@ spice to => 'https://api.flightstats.com/flex/flightstatus/rest/v2/jsonp/flight/
 spice from => '(.*)/(.*)/(.*)/(.*)/(.*)/(.*)';
 spice proxy_cache_valid => '418 1d';
 
-triggers any => '///***never trigger***///';
-# triggers query_lc => qr/^(\d+)\s+(.*?)(?:[ ]air.*?)?$|^(.*?)(?:[ ]air.*?)?\s+(\d+)$/;
```
Comment (marianosimone) [inline lib/DDG/Spice/Airlines.pm]: just re-enabling it

**Comment by mintsoft** [comment]
Cool LGTM; @moollaza can we get this on beta?

File: lib/DDG/Spice/Airlines.pm (hunk 1 above)
Comment (moollaza) [inline lib/DDG/Spice/Airlines.pm]: This should remain commented out -- we have a special internal trigger for this Instant Answer

**Comment by marianosimone** [comment]
@moollaza done!

**Comment by bsstoner** [comment]
👍
