### PR TITLE
JavaScript: Switch NPM to new API and tile view

### LINKED ISSUE #3098: JavaScript: Improving the NPM Package Search
It seems that this is a popular IA, but is failing to trigger on a lot of queries in the search space. It currently represents [1.81% of the search space](https://forum.duckduckhack.com/t/javascript-search-overview/94/14). We can improve this. I think this is because of:

  1) Triggers
  2) Spaces in package names
  3) People using DDG as if it were npm's onsite search engine.

The final point is important here. It seems there aren't a lot of queries looking for something specific, but rather a suggestion. ie. `json pretty print npm` or `npm json web token`. If we update the API endpoint to the below link, this should solve this problem and the specifics will still show up.

http://npmsearch.com/query?q=json+web+tokens&fields=name,description,repository,homepage,author

Documentation: https://github.com/nodesource/npmsearch

This should make it work just like the [CPAN spice](https://duckduckgo.com/?q=metacpan+WWW%3A%3ADuckDuckGo&ia=software&iai=9). 

One thing I have noticed about this API though, is it doesn't direct a link back to npm, rather both *homepage* and *repository* return the github source which is no good. Appending the package name to the URL `https://www.npmjs.com/package/` will redirect that though. 

------
IA Page:  https://duck.co/ia/view/npm
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @remixz

### PR DESCRIPTION
**Pull request by adampolar**
## Description of new Instant Answer, or changes
Changes from a single detail response to a search style response

## Related Issues and Discussions

Fixes #3098 
Note that this leaves the README.md with an image of the previous incarnation of the npm spice

## People to notify

@pjhampton

---

Instant Answer Page: https://duck.co/ia/view/npm

### CODE REVIEW

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

**Comment by adampolar** [comment]
Hi, sorry for the late change. I realised that the author is not always present in the package object and publisher looks like it is, so I decided to use that for the footer instead (this also matches the prominent display of the publisher on npmjs.com).

Another issue I wanted to ask about is the query stripping area of the code. I stole that from metacpan spice and slapped it in my own (I couldn't find a common area to use in this framework) but am a bit unsure that it's the right thing to do. In particular as it's digging out user input could it potentially be used for XSS attacks? Please could someone offer guidance on this?

**Comment by moollaza** [comment]
> I realised that the author is not always present in the package object and publisher looks like it is, so I decided to use that for the footer instead (this also matches the prominent display of the publisher on npmjs.com).

@adampolar That sounds fine 👍 

> but am a bit unsure that it's the right thing to do

Are you referring to lines 9-11?  If so, that's perfectly fine 👍

**Comment by adampolar** [comment]
> Are you referring to lines 9-11? If so, that's perfectly fine :+1:

@moollaza Yep that's it. Great thanks for the assurance.

File: lib/DDG/Spice/Npm.pm [hunk 1]
```diff
@@ -1,13 +1,17 @@
...
 
 use strict;
 use DDG::Spice;
+use warnings;
 
-triggers startend => 'npm', 'nodejs';
+spice is_cached => 1;
+spice proxy_cache_valid => '200 1d';
+
+triggers startend => 'npm', 'nodejs', 'node package';
```
Comment (moollaza) [inline lib/DDG/Spice/Npm.pm]: @adampolar please add `node js` -- I see that appearing a lot in the autocomplete suggestions!

File: share/spice/npm/npm.js [hunk 2]
```diff
@@ -2,96 +2,55 @@
...
+                
                 return {
-                    title: item.name + " " + item.version,
-                    subtitle: item.description,
-                    infoboxData: boxData,
+                    title: item.package.name,
+                    subtitle: "version: " + item.package.version,
+                    description: item.package.description,
+                    url: item.package.links.npm,
+                    rating: item.score.final.toFixed(2),
```
Comment (moollaza) [inline share/spice/npm/npm.js]: @adampolar it seems like we should be sorting results in order of decreasing rating?

I'm wondering if this is actually something we need to show to the user though because its an npms.io concept and it may not be clear what "score" means or where it's coming from.

For example, https://npms.io/search?q=wikipedia seems to have a 0.06 score before a 0.66 -- that seems like a sorting error we can handle on our end?

File: lib/DDG/Spice/Npm.pm (hunk 1 above)
Comment (adampolar) [inline lib/DDG/Spice/Npm.pm]: @moollaza Will do!

File: share/spice/npm/npm.js (hunk 2 above)
Comment (adampolar) [inline share/spice/npm/npm.js]: @moollaza 

> it seems like we should be sorting results in order of decreasing rating?

I'm not sure, I don't think it is a "search relevancy score", the score is actually about how well maintained etc. a package is.  it might throw up some weird ones, for example, mocha would then have enzyme as its first result. (see https://npms.io/search?q=mocha). The search relevancy score is provided by the searchScore value.

> I'm wondering if this is actually something we need to show to the user though because its an npms.io concept and it may not be clear what "score" means or where it's coming from.

I agree with this. Do you think the date parameter might be more relevant here?

**Comment by moollaza** [comment]
Deploying changes...

**Comment by moollaza** [comment]
@adampolar Thanks! This LGTM :+1:

Excellent work 💯

**Comment by adampolar** [comment]
Thanks @moollaza ! Do I need to update the page at  https://duck.co/ia/view/npm?

**Comment by moollaza** [comment]
> Thanks @moollaza ! Do I need to update the page at https://duck.co/ia/view/npm?

Nope!
