### PR TITLE
Coderwall: Update to handle markdown content from API (fixes #2548)

### LINKED ISSUE #2548: Coderwall: IA Broken, API Response Format Changed?
This IA is currently not working and there is a console error.

The Safari debugger suggests that the `$.each()` loop over `item.accounts` isn't working. 

It looks like the API response format has actually changed and now the code needs to be updated

------
IA Page:  http://duck.co/ia/view/coderwall
/cc @motersen

### PR DESCRIPTION
**Pull request by xaviervalarino**
This PR fixes the issue described in #2548 

Fixes include: 
* Changing the object passed to `normalize` to match the new Coderwall API response
* A custom handlebars helper to parse any markdown in `description`
* Profile avatar images included in `iconImage`

@moollaza suggested also using `chompContent` to hide descriptions that are too long, but I am not sure how to implement it.

CC: @GuiltyDolphin

---
IA Page: https://duck.co/ia/view/coderwall

### CODE REVIEW

**Comment by daxtheduck** [comment]
@xaviervalarino Hey!
        
Thanks for taking the time to contribute! We really appreciate it.

We work closely with every contributor to make Instant Answers the best they can be, so we appreciate your patience as we look over your code. From here, the process usually goes like this:

1. Pull Request is reviewed by the DuckDuckGo staff and community
2. Staff and community will leave feedback with any necessary updates to the function or design.
3. Once you've made any necessary corrections, then your Instant Answer will be merged and deployed live on DuckDuckGo!

If you have any questions along the way, feel free to ask them here. Our staff and community are also available on Slack to answer any questions you may have. If you'd like to join us there please send an email to <quackslack@duckduckgo.com>.

>More Info: https://duck.co/duckduckhack/submission_and_review

Thanks!

**Comment by daxtheduck** [comment]
Metadata placeholder post
            
*If you haven't already, please edit your first comment to include a link to the IA page at the bottom.*
            
---
            
**How to find your IA page**
- New Instant Answer
  -- follow the steps [here](https://duck.co/ia/new_ia) to create your IA page.
              
- Existing Instant Answer
  -- find your IA page from this [list](https://duck.co/ia)

File: share/spice/coderwall/coderwall.js [hunk 1]
```diff
@@ -58,8 +52,35 @@
...
+                options: {
+                    chompContents: true,
+                    content: DDH.coderwall.content
+                }
             }
         });
+
     };
+
+    Handlebars.registerHelper("parseMD", function(content){
```
Comment (GuiltyDolphin) [inline share/spice/coderwall/coderwall.js]: Did you get this from anywhere? If so it'd be useful to include a link to reference so peeps can check out more info.

Comment (xaviervalarino) [inline share/spice/coderwall/coderwall.js]: This is an original handlebars helper. It might be best to swtitch this one out with something that is tried-and-true. The only search result that seemed promising to me was [helper-markdown](https://github.com/helpers/helper-markdown) which has [remarkable](https://github.com/jonschlinkert/remarkable) as a dependency.

File: share/spice/coderwall/coderwall.js [hunk 2]
```diff
@@ -58,8 +52,35 @@
             },
 
             templates: {
-                group: 'icon'
+                group: 'icon',
+                variants: {
+                    iconImage: 'large'
+                },
+                options: {
+                    chompContents: true,
```
Comment (xaviervalarino) [inline share/spice/coderwall/coderwall.js]: I've been playing around with these two helpers by passing `parseMD` as a [subexpression](http://handlebarsjs.com/expressions.html#subexpressions), but have been getting some strange behavior. This is because the custom helper returns unescaped inline tags (`<em>`,`<strong>`,`<code>`,`<a href>`). The built-in helpers are counting the markup as part of the max length. This results in unclosed tags with `{{{Condense}}}`  and inconsistent counting with `{{{Ellipsis}}}`, _i.e._, it's counting the url characters in `href`.

Any ideas on the best way to count only the visible characters?

Comment (moollaza) [inline share/spice/coderwall/coderwall.js]: Looks like you figured it out?

`condense` is a block helper. It'll apply it's changes to the final value of whatever is inside it's block. It's built to prevent breaking HTML so something like this should work:

```handlebars
{{#condense 300}}
  {{parseMD description}}
{{/condesnse}}
```

Comment (xaviervalarino) [inline share/spice/coderwall/coderwall.js]: It looks like `condense` is no longer a block helper. [The example from the docs](http://docs.duckduckhack.com/frontend-reference/handlebars-helpers.html#condense) has it being used like so:
```handlebars
{{condense myString maxlen="135" truncation="..."}}
```

**Comment by xaviervalarino** [comment]
I force pushed this branch. I realized doing so is strongly discouraged only after reading through the original [PR for this IA](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1914). Sorry!

**Comment by GuiltyDolphin** [comment]
@xaviervalarino Don't look at any of my PRs :wink:

**Comment by moollaza** [comment]
Deploying to beta...

**Comment by moollaza** [comment]
@xaviervalarino I'm getting a JS error in the console:

jpcamara_coderwall_at_duckduckgo_and_coderwall__update_to_handle_markdown_content_from_api_by_xaviervalarino_ _pull_request__2632_ _duckduckgo_zeroclickinfo-spice

**Comment by moollaza** [comment]
@xaviervalarino false alarm, it looks like the code on Beta is still old... it's failing on `item.accounts` in the `$.each()` block which you've fixed here

**Comment by moollaza** [comment]
Deploying this to beta, again...

**Comment by moollaza** [comment]
@xaviervalarino alright the correct code is there now, but we have another problem. the input to the ellipsis function is causing problems. I think you're going to need to use the `condense` helper after all

**Comment by moollaza** [comment]
https://beta.duckduckgo.com/?q=coderwall+jpcamara&ia=social

coderwall_jpcamara_at_duckduckgo

**Comment by xaviervalarino** [comment]
@moollaza I've been having trouble with both helpers!

I update the `parseMD` helper to sanitize the account description and avoid any potential cross-site scripting. It returns a SafeString, which fully breaks `ellipsis` and causes `condense` to not trim the string.

Even when I just return a normal string, these helpers are still counting the characters in the HTML tags, which results in incomplete and malformed tags:

### condense
coderwall-condense
wraps the  _More at_ link into the unclosed tag

---
### ellipsis
coderwall-ellipsis
trimsWrites invalid markup

---

File: share/spice/coderwall/coderwall.js [hunk 3]
```diff
@@ -58,8 +52,32 @@
...
+    Handlebars.registerHelper("parseMD", function(content){
+        var contentArr = [];
+        if (!content) return;
+        else content.split(/\n+/).forEach(function(line) {
+            // exclude lines that are only whitespace characters
+            if (/[a-z0-9]/.test(line)) {
+                line = line.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>') // bold
+                  .replace(/(?:_(.+?)_|\*(.+?)\*)/g, '<em>$1$2</em>') // italicize
+                  .replace(/`(.+?)`/g, '<code>$1</code>') // monospace
+                  .replace(/~~(.+?)~~/g, '<del>$1</del>') // strikethrough
```
Comment (GuiltyDolphin) [inline share/spice/coderwall/coderwall.js]: If you need any help with HTML escaping check out [MarkdownReference](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/markdown_reference/markdown_reference.js) - I found a pretty good helper for it a while back.

**Comment by xaviervalarino** [comment]
> I've been having trouble with both helpers!

@moollaza I have a couple of ideas for how to work around this:
### Short Term
 1. Exclude built in helpers: don't trim the content and leave it as is
  * **UPSIDE:** Easy to implement, could get to production faster
  * **DOWNSIDE:** Longer descriptions could eat up most of the viewport, taking away from search results below
 1. Create a custom helper for the interim (see long term) to trim this specific type of string. I have been working on block helper that will do this, but haven't pushed any commits yet.
  * **UPSIDE:** Effective trimming that only counts visible characters and excludes markup
  * **DOWNSIDE:** More moving parts/ more likely to break

### Long Term
Create issues and/or PRs to `ellipsis` and `condense` to fix the following issues:
1. Better tag handling
2. Support SafeStrings (I already created [DDG template-helpers Issue #9](https://github.com/duckduckgo/duckduckgo-template-helpers/issues/9))
3. Propose an enhancement to optionally exclude markup, _e.g._, 
```handlebars
{{condense (parseMD description) maxleng='300' ignoretags='true' truncation='...'}}
...
{{ellipsis (parseMD description) 300 ignoreTags}}
```
Then come back and clean up the Codewall IA

(Sorry if this is a little didactic, I just had the impression we wanted to get this out the door sooner rather than later since #2548 is marked as a high priority issue.)

File: share/spice/coderwall/coderwall.js (hunk 3 above)
Comment (xaviervalarino) [inline share/spice/coderwall/coderwall.js]: Thanks for this! I can definitely see myself referring to those entities in the future. What do you mean by escaping the HTML, though? Wouldn't escaping it turn the description into a garbled mess of markup + text?

Comment (GuiltyDolphin) [inline share/spice/coderwall/coderwall.js]: For `code` blocks you can use it to ensure HTML doesn't decide to take it upon itself to start changing things. If you look in the Handlebars for MarkdownReference you'll see what I mean.

You might not need it, but it is there if you do.

**Comment by moollaza** [comment]
@xaviervalarino thanks again for improving the Coderwall Spice! You’ve been doing a really good job here and we'd like you to help our community tackle the next big challenge - our mission to become the best search engine for programmers: https://duck.co/blog/post/297/help-for-programmers.

When you're ready to move on, please: 

- Create a new Instant Answer to increase our Programming IA coverage

OR

- Test live programming Instant Answers (or those in development) for bugs and suggest improvements 

Detailed instructions explaining how you can help are available at the top of this [page](https://github.com/duckduckgo/duckduckgo/wiki/Programming-IA-Coverage).

Thanks again!

**Comment by xaviervalarino** [comment]
Finally got around to trying to close this PR, but have run into an issue that I don't know how to proceed.

coderwall-spice-failed
The console says that the Coderwall Spice has failed:
```
[NOTICE] Spice.failed() called by Spice with ID "coderwall"
```
I thought the issue might be caused by some of my new commits so I checked out an earlier one, but still get the same issue. Maybe it has something to do with the perl file?
 
~~It also looks like I get a 404 from https://coderwall.com/api
Maybe they changed/removed the API?~~

It looks like it's still sending back the same response:
https://coderwall.com/jpcamara.json?full=true&callback=ddg_spice_coderwall

**Comment by xaviervalarino** [comment]
@zachthompson I have added a css file to hide the white border that exists on some of the profile images for older account.

**Comment by xaviervalarino** [comment]
@moollaza i've created a custom block helper that trims any description over 250 characters to the closest word. I also created a [Codepen](https://codepen.io/xaviervalarino/pen/xVaqpy) that uses these helpers so that you can play around with different character limits and custom markdown.  

That sort of closes out everything I wanted to do for this IA, but let me know if there is anything else that you think might be missing.

**Comment by moollaza** [comment]
LGTM 👍
